// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {views} from '../models';

export function CreateActivity(arg1:string,arg2:string):Promise<models.Activity>;

export function CreateRecordingWithMode(arg1:string,arg2:string):Promise<views.RecordingSession>;

export function CreateTestActivity():Promise<Record<string, any>>;

export function DeleteActivity(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function GetActiveModel():Promise<models.WhisperModel>;

export function GetActivities():Promise<Array<models.Activity>>;

export function GetActivity(arg1:string):Promise<models.Activity>;

export function GetActivityTranscript(arg1:string):Promise<Array<models.TranscriptChunk>>;

export function GetAppStatus():Promise<string>;

export function GetAppStatusDetailed():Promise<Record<string, any>>;

export function GetAudioDevices():Promise<Array<Record<string, any>>>;

export function GetAvailableModels():Promise<Array<models.WhisperModel>>;

export function GetCurrentUser():Promise<Record<string, any>>;

export function GetDatabasePath():Promise<string>;

export function GetRecordingModes():Promise<Array<Record<string, any>>>;

export function GetRecordingTranscript(arg1:string):Promise<Array<models.TranscriptChunk>>;

export function GetSystemCapabilities():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetTranscript(arg1:string):Promise<Array<models.TranscriptChunk>>;

export function GetTranscriptionStatus(arg1:string):Promise<models.TranscriptionStatus>;

export function GetUserSettings():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function ListActivities():Promise<Record<string, any>>;

export function ProcessActivityTranscription(arg1:string):Promise<void>;

export function ProcessRecordingTranscription(arg1:string,arg2:string):Promise<void>;

export function QuitApp():Promise<void>;

export function SearchActivityTranscripts(arg1:string):Promise<Array<models.TranscriptChunk>>;

export function SearchTranscripts(arg1:string):Promise<Array<models.TranscriptChunk>>;

export function SetActiveModel(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartActivity(arg1:string):Promise<void>;

export function StartRecordingButtonAction():Promise<views.RecordingSession>;

export function StopActivity(arg1:string):Promise<void>;

export function StopRecordingButtonAction(arg1:string):Promise<void>;

export function UpdateActivityTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateActivityType(arg1:string,arg2:string):Promise<void>;

export function UpdateUserSettings(arg1:Record<string, any>):Promise<void>;
