// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateActivity(arg1, arg2) {
  return window['go']['main']['App']['CreateActivity'](arg1, arg2);
}

export function CreateRecordingWithMode(arg1, arg2) {
  return window['go']['main']['App']['CreateRecordingWithMode'](arg1, arg2);
}

export function CreateTestActivity() {
  return window['go']['main']['App']['CreateTestActivity']();
}

export function DeleteActivity(arg1) {
  return window['go']['main']['App']['DeleteActivity'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function GetActiveModel() {
  return window['go']['main']['App']['GetActiveModel']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetActivity(arg1) {
  return window['go']['main']['App']['GetActivity'](arg1);
}

export function GetActivityTranscript(arg1) {
  return window['go']['main']['App']['GetActivityTranscript'](arg1);
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetAppStatusDetailed() {
  return window['go']['main']['App']['GetAppStatusDetailed']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetRecordingModes() {
  return window['go']['main']['App']['GetRecordingModes']();
}

export function GetRecordingTranscript(arg1) {
  return window['go']['main']['App']['GetRecordingTranscript'](arg1);
}

export function GetSystemCapabilities() {
  return window['go']['main']['App']['GetSystemCapabilities']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTranscript(arg1) {
  return window['go']['main']['App']['GetTranscript'](arg1);
}

export function GetTranscriptionStatus(arg1) {
  return window['go']['main']['App']['GetTranscriptionStatus'](arg1);
}

export function GetUserSettings() {
  return window['go']['main']['App']['GetUserSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListActivities() {
  return window['go']['main']['App']['ListActivities']();
}

export function ProcessActivityTranscription(arg1) {
  return window['go']['main']['App']['ProcessActivityTranscription'](arg1);
}

export function ProcessRecordingTranscription(arg1, arg2) {
  return window['go']['main']['App']['ProcessRecordingTranscription'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SearchActivityTranscripts(arg1) {
  return window['go']['main']['App']['SearchActivityTranscripts'](arg1);
}

export function SearchTranscripts(arg1) {
  return window['go']['main']['App']['SearchTranscripts'](arg1);
}

export function SetActiveModel(arg1) {
  return window['go']['main']['App']['SetActiveModel'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartActivity(arg1) {
  return window['go']['main']['App']['StartActivity'](arg1);
}

export function StartRecordingButtonAction() {
  return window['go']['main']['App']['StartRecordingButtonAction']();
}

export function StopActivity(arg1) {
  return window['go']['main']['App']['StopActivity'](arg1);
}

export function StopRecordingButtonAction(arg1) {
  return window['go']['main']['App']['StopRecordingButtonAction'](arg1);
}

export function UpdateActivityTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateActivityTitle'](arg1, arg2);
}

export function UpdateActivityType(arg1, arg2) {
  return window['go']['main']['App']['UpdateActivityType'](arg1, arg2);
}

export function UpdateUserSettings(arg1) {
  return window['go']['main']['App']['UpdateUserSettings'](arg1);
}
